### ISSUE TITLE
Launch Emacs instead of VSCode

### ISSUE THREAD

**Issue by muep** [gasinvein/vscode-flatpak-wrapper#3]
Hi @gasinvein ,

I am working on adding [SDK support to Emacs](https://github.com/flathub/org.gnu.emacs/issues/31). Seeing what this wrapper does was my original inspiration on wanting that same thing in the Emacs flatpak, and it turns out that it pretty much already can do it.

There are some bits I would need to change, and I would like to ask if it would be preferable to just fork this repo and keep Emacs stuff out of your way, or if you would prefer to have those changes here. I am OK doing it either way, but it might be useful if the various IDE-like flatpaks handled SDK extensions similarly. At least for Jetbrains, there seems to already exist a [fork](https://github.com/Lctrs/jetbrains-flatpak-wrapper) of this wrapper.

**Comment by gasinvein** [comment]
I'm totally fine with generalizing this wrapper so it can support other editors. One thing I'd like to avoid, though, is special cases - if possible, configure all editor-specific things as meson options.

**Comment by gasinvein** [comment]
Is this issue resolved now?

**Comment by muep** [comment]
It is resolved. Thank you for the support in addressing this.
