### ISSUE TITLE
suggestion: add instructions for permanently adding an SDK to first_run.txt

### ISSUE THREAD

**Issue by johanmcos** [gasinvein/vscode-flatpak-wrapper#6]
Thank you for this wrapper, I've used many flatpaks that derive from it and they're all wonderful.

Anyways, in first_run.txt, it gives good instructions for how to find and install more sdks, but only mentions how to enable them at the time that the flatpak is invoked.

I think it would be convenient to also instruct users how to permanently enable an sdk using the command:
`flatpak overrride @FLATPAK_ID@ --env=FLATPAK_ENABLE_SDK_EXT=node14`

There's of course other ways to do this, like altering the .desktop file, creating a custom launch script, etc. but I think this is by far the simplest since it's a command you run once

**Comment by gasinvein** [comment]
Sorry for the late response, I've somehow unwatched this repo and missed the issue (along with some others).

This makes sense. Although one should probably use `--user` option for `flatpak override`.

**Comment by gasinvein** [comment]
Pushed e186e2e, thanks for the suggestion. If you'd like to improve wording  or something - feel free to send a PR.
